// Global Component Styles
// All component styles converted from index.css to JavaScript objects
// Uses camelCase properties for JSX compatibility

export const heroStyles = {
  section: {
    minHeight: '100vh',
    padding: '90px 40px 60px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
    overflow: 'visible',
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '70px',
    width: '100%',
    alignItems: 'center',
    position: 'relative',
  },
  heroContent: {
    display: 'flex',
    flexDirection: 'column',
  },
  greeting: {
    fontSize: '16px',
    color: '#ff6b81',
    marginBottom: '12px',
    fontWeight: 600,
    letterSpacing: '0.5px',
  },
  h1: {
    fontSize: '60px',
    lineHeight: 1.2,
    marginBottom: '24px',
    fontWeight: 800,
    letterSpacing: '-1.5px',
  },
  highlight: {
    background: 'linear-gradient(135deg, #ff6b9d, #ff4d7a)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    color: '#999',
    marginBottom: '20px',
    fontSize: '18px',
    fontWeight: 500,
    letterSpacing: '0.3px',
  },
  paragraph: {
    lineHeight: 1.7,
    color: '#c4c4c4',
    marginBottom: '32px',
    fontSize: '16px',
    maxWidth: '480px',
  },
  tags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    margin: '35px 0',
  },
  tag: {
    background: 'rgba(255, 71, 87, 0.08)',
    border: '1px solid rgba(255, 71, 87, 0.15)',
    padding: '9px 18px',
    borderRadius: '20px',
    fontSize: '13px',
    color: '#ff8fa3',
    fontWeight: 500,
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    cursor: 'pointer',
    position: 'relative',
    overflow: 'hidden',
  },
  ctaButtons: {
    display: 'flex',
    gap: '14px',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, #ff6b9d, #ff5a8a)',
    color: '#fff',
    border: 'none',
    padding: '14px 32px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 700,
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    textDecoration: 'none',
    display: 'inline-block',
    boxShadow: '0 4px 16px rgba(255, 107, 157, 0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
  btnSecondary: {
    background: 'transparent',
    color: '#ff8fa3',
    border: '1.5px solid rgba(255, 107, 157, 0.3)',
    padding: '12px 30px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 700,
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    textDecoration: 'none',
    display: 'inline-block',
    position: 'relative',
  },
  splineContainer: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '500px',
  },
  socialRow: {
    display: 'flex',
    gap: '14px',
    marginTop: '18px',
  },
  socialBtn: {
    width: '46px',
    height: '46px',
    borderRadius: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255, 255, 255, 0.06)',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    color: '#fff',
    fontSize: '20px',
    cursor: 'pointer',
    position: 'relative',
    overflow: 'hidden',
    backdropFilter: 'blur(12px)',
    transition: 'all 0.35s ease',
  },
  ctaWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    alignItems: 'flex-start',
  },
};

export const aboutStyles = {
  section: {
    display: 'grid',
    gridTemplateColumns: '1.1fr 0.9fr',
    gridTemplateRows: 'auto auto auto',
    gap: '50px 70px',
    alignItems: 'start',
    justifyItems: 'stretch',
    width: '100%',
    padding: '60px 40px',
    background: 'radial-gradient(circle at right, #4b0f2a, #140013 60%)',
    position: 'relative',
  },
  header: {
    gridColumn: '1 / -1',
    gridRow: 1,
    textAlign: 'center',
    marginBottom: '40px',
    padding: '0 20px',
  },
  title: {
    fontSize: '3rem',
    fontWeight: 800,
    margin: '0 0 12px 0',
    background: 'linear-gradient(135deg, #6366f1, #a855f7)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-1px',
  },
  subtitle: {
    fontSize: '15px',
    color: '#a0aec0',
    fontWeight: 500,
    letterSpacing: '0.5px',
    margin: 0,
  },
  left: {
    gridColumn: 1,
    gridRow: 2,
    color: '#fff',
    position: 'relative',
    padding: '40px 36px',
    maxWidth: '580px',
    background: 'rgba(255, 255, 255, 0.04)',
    backdropFilter: 'blur(18px)',
    borderRadius: '18px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: '0 30px 80px rgba(0, 0, 0, 0.45), inset 0 0 0 1px rgba(255, 255, 255, 0.03)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    zIndex: 2,
  },
  greeting: {
    display: 'block',
    fontSize: '13px',
    color: '#ff8fa3',
    fontWeight: 600,
    marginBottom: '12px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  name: {
    fontSize: '3.2rem',
    fontWeight: 800,
    margin: '8px 0 16px 0',
    lineHeight: 1.1,
    letterSpacing: '-0.8px',
  },
  role: {
    fontSize: '15px',
    color: '#a89fff',
    marginBottom: '18px',
    fontWeight: 500,
    letterSpacing: '0.3px',
  },
  text: {
    fontSize: '15px',
    maxWidth: '100%',
    lineHeight: 1.7,
    opacity: 0.9,
    color: '#d0d0d0',
    marginBottom: '16px',
  },
  quote: {
    marginTop: '20px',
    fontSize: '13px',
    fontStyle: 'italic',
    color: '#ffb3c1',
    borderLeft: '3px solid rgba(255, 107, 157, 0.4)',
    paddingLeft: '16px',
    lineHeight: 1.6,
    opacity: 0.85,
  },
  right: {
    gridColumn: 2,
    gridRow: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    minHeight: '400px',
  },
  image: {
    position: 'relative',
    width: '340px',
    height: '340px',
    borderRadius: '50%',
    padding: '6px',
    background: 'linear-gradient(135deg, #ff4d6d, #7a1fa2)',
    animation: 'float 6s ease-in-out infinite',
    boxShadow: '0 40px 120px rgba(0, 0, 0, 0.6), 0 0 0 12px rgba(255, 77, 109, 0.12)',
    zIndex: 1,
  },
  imageImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '50%',
  },
  stats: {
    gridColumn: '1 / -1',
    gridRow: 3,
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
    marginTop: 0,
    width: '100%',
    padding: '0 20px',
  },
  statCard: {
    padding: '28px 24px',
    borderRadius: '16px',
    background: 'linear-gradient(145deg, rgba(255, 255, 255, 0.08), rgba(255, 255, 255, 0.02))',
    backdropFilter: 'blur(14px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    textAlign: 'center',
    transition: 'all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    cursor: 'pointer',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.4)',
  },
  statCardH3: {
    fontSize: '32px',
    color: '#ff8fa3',
    marginBottom: '8px',
    fontWeight: 700,
    marginTop: 0,
  },
  statCardP: {
    fontSize: '13px',
    opacity: 0.8,
    margin: 0,
    letterSpacing: '0.3px',
  },
};

export const portfolioStyles = {
  section: {
    position: 'relative',
    overflow: 'hidden',
    background: 'linear-gradient(180deg, rgba(139,133,255,0.12), transparent), repeating-linear-gradient(90deg, rgba(255,255,255,0.04) 0px, rgba(255,255,255,0.04) 1px, transparent 1px, transparent 40px), repeating-linear-gradient(0deg, rgba(255,255,255,0.04) 0px, rgba(255,255,255,0.04) 1px, transparent 1px, transparent 40px), #0b061a',
  },
  portfolioSection: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 40px',
  },
  tabs: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    marginBottom: '40px',
    flexWrap: 'wrap',
    position: 'relative',
    zIndex: 1,
  },
  tabButton: {
    background: 'rgba(255, 255, 255, 0.05)',
    border: '1.5px solid rgba(255, 71, 87, 0.2)',
    color: '#ccc',
    padding: '14px 36px',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    fontSize: '15px',
    fontWeight: 600,
    position: 'relative',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  filters: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '48px',
    flexWrap: 'wrap',
    position: 'relative',
    zIndex: 1,
  },
  filterPill: {
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 71, 87, 0.15)',
    color: '#aaa',
    padding: '10px 22px',
    borderRadius: '20px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontSize: '13px',
    fontWeight: 500,
    whiteSpace: 'nowrap',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '28px',
    width: '100%',
    position: 'relative',
    zIndex: 1,
    boxSizing: 'border-box',
  },
  card: {
    background: 'linear-gradient(145deg, rgba(139,133,255,0.18), rgba(139,133,255,0.06))',
    borderRadius: '18px',
    border: '1.5px solid rgba(139,133,255,0.25)',
    backdropFilter: 'blur(18px)',
    WebkitBackdropFilter: 'blur(18px)',
    boxShadow: '0 20px 60px rgba(0,0,0,0.45), inset 0 0 0 1px rgba(255,255,255,0.06)',
    transition: 'all 0.35s ease',
    cursor: 'pointer',
    overflow: 'hidden',
  },
  cardImageWrapper: {
    width: '100%',
    height: '160px',
    background: 'linear-gradient(135deg, rgba(255, 71, 87, 0.08) 0%, rgba(255, 107, 157, 0.04) 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    borderBottom: '1px solid rgba(255, 71, 87, 0.1)',
  },
  cardIcon: {
    fontSize: '56px',
    filter: 'drop-shadow(0 2px 8px rgba(0, 0, 0, 0.3))',
  },
  cardContent: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    flexGrow: 1,
    position: 'relative',
    zIndex: 3,
  },
  cardLabel: {
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '1px',
    color: '#b7b4ff',
    transition: 'color 0.3s ease',
  },
  cardTitle: {
    fontSize: '17px',
    fontWeight: 700,
    color: '#fff',
    lineHeight: 1.3,
    margin: 0,
  },
  cardDescription: {
    fontSize: '12px',
    color: '#aaa',
    lineHeight: 1.5,
    margin: 0,
    flexGrow: 1,
  },
};

export const contactStyles = {
  section: {
    background: 'transparent',
  },
  container: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.2fr',
    gap: '70px',
    width: '100%',
  },
  info: {
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
  },
  infoHeading: {
    fontSize: '32px',
    color: '#fff',
    marginBottom: '20px',
    fontWeight: 700,
  },
  infoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    background: 'rgba(255, 255, 255, 0.03)',
    padding: '20px 24px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
  },
  infoIcon: {
    fontSize: '30px',
    minWidth: '50px',
    textAlign: 'center',
  },
  form: {
    background: 'rgba(255, 255, 255, 0.03)',
    padding: '36px',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  label: {
    color: '#ccc',
    fontWeight: 600,
    fontSize: '15px',
  },
  input: {
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    padding: '14px 16px',
    borderRadius: '10px',
    color: '#fff',
    fontFamily: 'inherit',
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    fontSize: '14px',
  },
  textarea: {
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    padding: '14px 16px',
    borderRadius: '10px',
    color: '#fff',
    fontFamily: 'inherit',
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    fontSize: '14px',
    minHeight: '160px',
    resize: 'vertical',
  },
  submitBtn: {
    background: 'linear-gradient(135deg, #ff6b9d, #ff5a8a)',
    color: '#fff',
    border: 'none',
    padding: '13px 36px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 700,
    transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    boxShadow: '0 4px 16px rgba(255, 107, 157, 0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
};

export const footerStyles = {
  footer: {
    textAlign: 'center',
    padding: '30px',
    color: '#666',
    borderTop: '1px solid rgba(255, 255, 255, 0.05)',
    position: 'relative',
    zIndex: 2,
  },
};

export const globalAnimations = {
  '@keyframes fadeInLeft': {
    from: { opacity: 0, transform: 'translateX(-50px)' },
    to: { opacity: 1, transform: 'translateX(0)' },
  },
  '@keyframes fadeInRight': {
    from: { opacity: 0, transform: 'translateX(50px)' },
    to: { opacity: 1, transform: 'translateX(0)' },
  },
  '@keyframes float': {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-20px)' },
  },
  '@keyframes rotate': {
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
  },
  '@keyframes floatAround': {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-20px)' },
  },
};
